# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace/ix/FasterTransformer-master_2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace/ix/FasterTransformer-master_2/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/ix/FasterTransformer-master_2/build/CMakeFiles /workspace/ix/FasterTransformer-master_2/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/ix/FasterTransformer-master_2/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named copy

# Build rule for target.
copy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 copy
.PHONY : copy

# fast build rule for target.
copy/fast:
	$(MAKE) -f CMakeFiles/copy.dir/build.make CMakeFiles/copy.dir/build
.PHONY : copy/fast

#=============================================================================
# Target rules for targets named gemm_fp16

# Build rule for target.
gemm_fp16: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gemm_fp16
.PHONY : gemm_fp16

# fast build rule for target.
gemm_fp16/fast:
	$(MAKE) -f tools/gemm_test/CMakeFiles/gemm_fp16.dir/build.make tools/gemm_test/CMakeFiles/gemm_fp16.dir/build
.PHONY : gemm_fp16/fast

#=============================================================================
# Target rules for targets named gemm_fp32

# Build rule for target.
gemm_fp32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gemm_fp32
.PHONY : gemm_fp32

# fast build rule for target.
gemm_fp32/fast:
	$(MAKE) -f tools/gemm_test/CMakeFiles/gemm_fp32.dir/build.make tools/gemm_test/CMakeFiles/gemm_fp32.dir/build
.PHONY : gemm_fp32/fast

#=============================================================================
# Target rules for targets named fastertransformer

# Build rule for target.
fastertransformer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fastertransformer
.PHONY : fastertransformer

# fast build rule for target.
fastertransformer/fast:
	$(MAKE) -f fastertransformer/cuda/CMakeFiles/fastertransformer.dir/build.make fastertransformer/cuda/CMakeFiles/fastertransformer.dir/build
.PHONY : fastertransformer/fast

#=============================================================================
# Target rules for targets named tf_fastertransformer

# Build rule for target.
tf_fastertransformer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tf_fastertransformer
.PHONY : tf_fastertransformer

# fast build rule for target.
tf_fastertransformer/fast:
	$(MAKE) -f fastertransformer/tf_op/CMakeFiles/tf_fastertransformer.dir/build.make fastertransformer/tf_op/CMakeFiles/tf_fastertransformer.dir/build
.PHONY : tf_fastertransformer/fast

#=============================================================================
# Target rules for targets named transformer_fp16

# Build rule for target.
transformer_fp16: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transformer_fp16
.PHONY : transformer_fp16

# fast build rule for target.
transformer_fp16/fast:
	$(MAKE) -f sample/cpp/CMakeFiles/transformer_fp16.dir/build.make sample/cpp/CMakeFiles/transformer_fp16.dir/build
.PHONY : transformer_fp16/fast

#=============================================================================
# Target rules for targets named transformer_fp32

# Build rule for target.
transformer_fp32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transformer_fp32
.PHONY : transformer_fp32

# fast build rule for target.
transformer_fp32/fast:
	$(MAKE) -f sample/cpp/CMakeFiles/transformer_fp32.dir/build.make sample/cpp/CMakeFiles/transformer_fp32.dir/build
.PHONY : transformer_fp32/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... copy"
	@echo "... gemm_fp16"
	@echo "... gemm_fp32"
	@echo "... fastertransformer"
	@echo "... tf_fastertransformer"
	@echo "... transformer_fp16"
	@echo "... transformer_fp32"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

